/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx,web.js,web.jsx,web.ts,web.tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#005994',
        'primary-container': '#0072bb',
        'on-primary': '#ffffff',
        'on-primary-container': '#ebf2ff',
        'primary-fixed': '#d0e4ff',
        'primary-fixed-dim': '#9ccaff',
        secondary: '#bc000d',
        'secondary-container': '#ea0515',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#ffdad5',
        'secondary-fixed-dim': '#ffb4aa',
        'on-secondary-fixed': '#410001',
        'on-secondary-fixed-variant': '#930008',
        tertiary: '#6f5028',
        'tertiary-container': '#8a683d',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffddb7',
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-dim': '#d8dae0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3fa',
        'surface-container': '#eceef4',
        'surface-container-high': '#e6e8ef',
        'surface-container-highest': '#e0e2e9',
        'surface-variant': '#e0e2e9',
        'inverse-surface': '#2d3136',
        'on-surface': '#181c21',
        'on-surface-variant': '#404751',
        'on-background': '#181c21',
        'inverse-on-surface': '#eef1f7',
        outline: '#717882',
        'outline-variant': '#c0c7d2',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        editorial: '0 12px 40px -4px rgba(24,28,33,0.06)',
        'nav-bottom': '0 -12px 40px -4px rgba(0,0,0,0.06)',
      },
    },
  },
  plugins: [],
};
