#!/usr/bin/env python3
"""Add missing i18n keys to locale JSON files.

This script reads the `missing_keys_report.json` generated by the
scan_translation_keys tool, extracts each missing translation key, and
adds it to `en.json`, `fr.json`, and `ar.json` if the key does not already
exist.

- English placeholders are generated from the key name (title‑cased).
- French and Arabic placeholders are left empty (""), to be filled by
a translator later.

The script overwrites the locale files in‑place, preserving formatting
(indent=2). It also creates a backup copy with the `.bak` extension before
modifying each file.
"""
import json
import os
import re
from pathlib import Path

# Paths (relative to project root)
PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOCALES_DIR = PROJECT_ROOT / "src" / "i18n" / "locales"
REPORT_PATH = PROJECT_ROOT / "scratch" / "missing_keys_report.json"

def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open(encoding="utf-8") as f:
        return json.load(f)

def save_json(data: dict, path: Path):
    # Write a backup first
    backup = path.with_suffix(path.suffix + ".bak")
    if path.exists():
        path.replace(backup)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

def human_placeholder(key: str) -> str:
    # Convert snake‑case or dot‑separated keys to a readable string
    parts = re.split(r"[._]", key)
    words = [p.capitalize() for p in parts if p]
    return " ".join(words)

def main():
    # Load missing keys report
    with REPORT_PATH.open(encoding="utf-8") as f:
        report = json.load(f)
    missing_keys = [item["key"] for item in report]

    # Process each locale
    for locale in ["en", "fr", "ar"]:
        locale_path = LOCALES_DIR / f"{locale}.json"
        data = load_json(locale_path)
        added = 0
        for key in missing_keys:
            # Nested keys handling – assume flat structure for simplicity
            if key not in data:
                if locale == "en":
                    data[key] = human_placeholder(key)
                else:
                    data[key] = ""
                added += 1
        if added:
            save_json(data, locale_path)
            print(f"Added {added} keys to {locale_path.name}")
        else:
            print(f"No new keys for {locale_path.name}")

if __name__ == "__main__":
    main()
